# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: screego
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
      - ppc64le
    goarm:
      - "6"
      - "7"
    flags:
      - '-tags="netgo osusergo"'
    ldflags:
      - "-s"
      - "-w"
      - "-X main.version={{.Version}}"
      - "-X main.commitHash={{.Commit}}"
      - "-X main.mode=prod"
archives:
  - files:
      - LICENSE
      - README.md
      - screego.config.example
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{- if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
checksum:
  disable: true
changelog:
  skip: true
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    goarm: ""
    image_templates:
      - "screego/server:amd64-unstable"
      - "screego/server:amd64-{{ .RawVersion }}"
      - "screego/audio/server:amd64-{{ .RawVersion }}-audio"
      - "screego/server:amd64-{{ .Major }}"
      - "ghcr.io/screego/server:amd64-unstable"
      - "ghcr.io/screego/server:amd64-{{ .RawVersion }}"
      - "ghcr.io/screego/server:amd64-{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: "386"
    goarm: ""
    image_templates:
      - "screego/server:386-unstable"
      - "screego/server:386-{{ .RawVersion }}"
      - "screego/audio/server:386-{{ .RawVersion }}-audio"
      - "screego/server:386-{{ .Major }}"
      - "ghcr.io/screego/server:386-unstable"
      - "ghcr.io/screego/server:386-{{ .RawVersion }}"
      - "ghcr.io/screego/server:386-{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/386"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    goarm: ""
    image_templates:
      - "screego/server:arm64-unstable"
      - "screego/server:arm64-{{ .RawVersion }}"
      - "screego/audio/server:arm64-{{ .RawVersion }}-audio"
      - "screego/server:arm64-{{ .Major }}"
      - "ghcr.io/screego/server:arm64-unstable"
      - "ghcr.io/screego/server:arm64-{{ .RawVersion }}"
      - "ghcr.io/screego/server:arm64-{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    image_templates:
      - "screego/server:armv7-unstable"
      - "screego/server:armv7-{{ .RawVersion }}"
      - "screego/audio/server:armv7-{{ .RawVersion }}"
      - "screego/server:armv7-{{ .Major }}"
      - "ghcr.io/screego/server:armv7-unstable"
      - "ghcr.io/screego/server:armv7-{{ .RawVersion }}"
      - "ghcr.io/screego/server:armv7-{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 6
    image_templates:
      - "screego/server:armv6-unstable"
      - "screego/server:armv6-{{ .RawVersion }}"
      - "screego/audio/server:armv6-{{ .RawVersion }}-audio"
      - "screego/server:armv6-{{ .Major }}"
      - "ghcr.io/screego/server:armv6-unstable"
      - "ghcr.io/screego/server:armv6-{{ .RawVersion }}"
      - "ghcr.io/screego/server:armv6-{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: ppc64le
    goarm: ""
    image_templates:
      - "screego/server:ppc64le-unstable"
      - "screego/server:ppc64le-{{ .RawVersion }}"
      - "screego/audio/server:ppc64le-{{ .RawVersion }}-audio"
      - "screego/server:ppc64le-{{ .Major }}"
      - "ghcr.io/screego/server:ppc64le-unstable"
      - "ghcr.io/screego/server:ppc64le-{{ .RawVersion }}"
      - "ghcr.io/screego/server:ppc64le-{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/ppc64le"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: "ghcr.io/screego/server:unstable"
    image_templates:
      - "ghcr.io/screego/server:amd64-unstable"
      - "ghcr.io/screego/server:386-unstable"
      - "ghcr.io/screego/server:arm64-unstable"
      - "ghcr.io/screego/server:armv7-unstable"
      - "ghcr.io/screego/server:armv6-unstable"
      - "ghcr.io/screego/server:ppc64le-unstable"
  - name_template: "screego/server:unstable"
    image_templates:
      - "screego/server:amd64-unstable"
      - "screego/server:386-unstable"
      - "screego/server:arm64-unstable"
      - "screego/server:armv7-unstable"
      - "screego/server:armv6-unstable"
      - "screego/server:ppc64le-unstable"
  - name_template: "screego/server:{{ .RawVersion }}"
    image_templates:
      - "screego/server:amd64-{{ .RawVersion }}"
      - "screego/server:386-{{ .RawVersion }}"
      - "screego/server:arm64-{{ .RawVersion }}"
      - "screego/server:armv7-{{ .RawVersion }}"
      - "screego/server:armv6-{{ .RawVersion }}"
      - "screego/server:ppc64le-{{ .RawVersion }}"
  - name_template: "ghcr.io/screego/server:{{ .RawVersion }}"
    image_templates:
      - "ghcr.io/screego/server:amd64-{{ .RawVersion }}"
      - "ghcr.io/screego/server:386-{{ .RawVersion }}"
      - "ghcr.io/screego/server:arm64-{{ .RawVersion }}"
      - "ghcr.io/screego/server:armv7-{{ .RawVersion }}"
      - "ghcr.io/screego/server:armv6-{{ .RawVersion }}"
      - "ghcr.io/screego/server:ppc64le-{{ .RawVersion }}"
  - name_template: "screego/server:{{ .Major }}"
    image_templates:
      - "screego/server:amd64-{{ .Major }}"
      - "screego/server:386-{{ .Major }}"
      - "screego/server:arm64-{{ .Major }}"
      - "screego/server:armv7-{{ .Major }}"
      - "screego/server:armv6-{{ .Major }}"
      - "screego/server:ppc64le-{{ .Major }}"
  - name_template: "ghcr.io/screego/server:{{ .Major }}"
    image_templates:
      - "ghcr.io/screego/server:amd64-{{ .Major }}"
      - "ghcr.io/screego/server:386-{{ .Major }}"
      - "ghcr.io/screego/server:arm64-{{ .Major }}"
      - "ghcr.io/screego/server:armv7-{{ .Major }}"
      - "ghcr.io/screego/server:armv6-{{ .Major }}"
      - "ghcr.io/screego/server:ppc64le-{{ .Major }}"
